# -*- coding: utf-8 -*-
"""EDA_Friends_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3ksfjzC89fItw5lc9xBqxI0ndormrXr
"""

import numpy as np
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Nicocasa26/friends/refs/heads/main/friends_july_2024.csv')

"""# Informacion de Data Frame

A continuacion usamos metodos para tener mas informacion del DataFrame
"""

df.describe()

df.describe().T #Los traspolamos

df.info()

df.shape

df.dtypes

df.head()

"""# Refinamiento de DF - Datos nulos

Empiezo con el refinamiento del DataFrame. Buscamos cuantos nulos hay.
Como en este DF no hay nulos, lo que opte es transformar algunas celdas a nulos para poder, posteriormente usar estrategias para solucionarlo.
"""

print(df.isnull().sum())

df.at[ 20, 'duration_in_minutes'] = np.nan #Transformamos  datos en nulos
df.at[19, 'duration_in_minutes'] = np.nan
df.at[60, 'episode'] = np.nan

print (df.loc[20, 'duration_in_minutes'] )#Verificamos que se haya borrado lo que pedimos
print (df.loc[19, 'duration_in_minutes'])
print (df.loc[60, 'episode'])

print(df.isnull().sum()) #mostramos las columnas que tienen nulos

"""A continuacion buscamos que filas, dentro de las columnas son nulas."""

df[df['duration_in_minutes'].isnull()]

df[df['episode'].isnull()]

"""Como los faltantes son en las columnas duracion de minutos y de N° de  episodio de la temporadas, vamos a usar dos estrategias diferentes, para la columna "Duracion en minutos" vamos a hacer un promedio de la duracion de los episodios de esa temporada.
Para los faltantes de la columna "Episodio", al comprobar que estan ordenado por numero temporada y cada temporada esta ordenado por episodio lo que vamos hacer es calcular que espisodio seria el faltante.

"""

season_1 = df[df['season'] == 1]
season_1

promedio_duracion = season_1['duration_in_minutes'].mean()
promedio_duracion

df['duration_in_minutes'].fillna(promedio_duracion, inplace=True) #No entendi porque me hace esa aclaracion

#Comprobamos si se hizo el reemplazo
df.loc[19,"duration_in_minutes"]

df.loc[20,"duration_in_minutes"]

print(df.isnull().sum()) #mostramos las columnas que tienen nulos

"""Ahora vamos deducir que episodio corresponderia al dato faltante en la columna "Episode"
"""

valor_reemplazo = df.loc[61, 'episode'] - 1
valor_reemplazo

df['episode'].fillna(valor_reemplazo, inplace=True)

df.loc[60, 'episode']

print(df.isnull().sum()) #Comprobamos que ya no hay nulos en el DF

"""---


# Hipostesis:

1.   Queremos saber cual es el episodio con mejor y peor puntuacion de la serie.
2.   Queremos saber cual es el mejor episodio de cada director.
3.   Queremos saber cual es el mejor director

# 1. Queremos saber cual es el episodio con mejor y peor puntuacion de la serie.
"""

cap_mejor = df['rating'].max()
fila_max = df.loc[df['rating'] == cap_mejor]
print(fila_max)

print("Datos del episodio mejor valorado\n")


titulo = fila_max['episode_title'].values[0]
print("Nombre de episodio : " + titulo)


temporada_max = fila_max['season'].values[0]
print("Temporada : " + str(temporada_max))


episodio_max = fila_max['episode'].values[0]
print("Episodio : " + str(episodio_max))


descripcion_max = fila_max['description'].values[0]
print("Descripcion del capitulo:\n" + str(descripcion_max))

print("Valoracion: " + str(cap_mejor))

cap_peor = df['rating'].min()
fila_min = df.loc[df['rating'] == cap_peor]
print(fila_min)

print("Datos del episodio peor valorado\n")


titulo2 = fila_min['episode_title'].values[0]
print("Nombre de episodio : " + titulo)


temporada_min = fila_min['season'].values[0]
print("Temporada : " + str(temporada_min))


episodio_min = fila_min['episode'].values[0]
print("Episodio : " + str(episodio_min))


descripcion_min = fila_min['description'].values[0]
print("Descripcion del capitulo:\n" + str(descripcion_min))

print("Valoracion: " + str(cap_peor))

"""# 2. Queremos saber cual es el mejor episodio de cada director."""

# Encuentra el índice del episodio con el rating más alto para cada director.
mejor_episodio = df.groupby('director')['rating'].idxmax()

# Usa los índices para obtener las filas correspondientes.
mejores_episodios = df.loc[mejor_episodio]

# Itero sobre los índices y para imprimir los datos.
for n in mejores_episodios.index:
    director = mejores_episodios.loc[n, 'director']
    rating = mejores_episodios.loc[n, 'rating']
    episode_title = mejores_episodios.loc[n, 'episode_title']
    season = mejores_episodios.loc[n, 'season']

    print(f"Director: {director}")
    print(f"Ranking: {rating}")
    print(f"Episodio: {episode_title}")
    print(f"Temporada: {season}")
    print("-" * 20)

"""# 3. Queremos saber cual es el mejor director"""

promedio_ratings = df.groupby('director')['rating'].mean().reset_index()

print(promedio_ratings)

top_director = promedio_ratings['rating'].max()
fila_mejor_director = promedio_ratings.loc[promedio_ratings['rating'] == top_director]

print(fila_mejor_director)

"""# 4. Queremos saber como es la tendencia del rating a lo largo de los años/temporadas."""

ratings_por_temporada = df.groupby('season')['rating'].mean().reset_index()

print(ratings_por_temporada)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(ratings_por_temporada['season'], ratings_por_temporada['rating'], marker='o', linestyle='-', color='b')
plt.title('Evolución del Rating por Temporada')
plt.xlabel('Temporada')
plt.ylabel('Rating Promedio')
plt.grid(True)
plt.xticks(range(1, df['season'].max() + 1))
plt.show()

"""Aca vemos claramente que la calidad de la serie (Basandonos solamente en el promedio del rating por temporada) va creciendo hasta tocar su pico maximo en la temporada 5 y de ahi empieza a bajar la calidad del programa.
La tmeporada 10, considero que hay excluirla de este analisas ya que al ser la ultima, seguramente el promeido del rating es mas alto por ese mismo motivo.

# Graficos

Aca vemos cuantos captiulos tienen el rating.
"""

plt.figure(figsize=(10, 6))
plt.bar(promedio_ratings['director'], promedio_ratings['rating'], color='skyblue')

plt.xlabel('Director', fontsize=12)
plt.ylabel('Promedio de Rating', fontsize=12)
plt.title('Promedio de Ratings por Director', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=10)  # giro las etiquetas para que sean legibles.
plt.grid(axis='y', linestyle='--', alpha=0.7)  # Agrego una cuadricula

"""En el siguiente Grafico podemos analizar cuantos capitulos (por año) son outlier. En este caso los outlier que estan por arriba, son los episodios con mejor puntaje y por el contrario los que estan abajo, lo que peor puntaje tienen."""

plt.figure(figsize=(10, 6))
df.boxplot(column='rating', by='year')
plt.xlabel('Año')
plt.ylabel('Rating')
plt.title('Distribución de Ratings por Año')
plt.show()

"""Con el siguiente grafico podes observar los mejores episodio de cada director."""

plt.figure(figsize=(10, 6))
plt.barh(mejores_episodios['director'], mejores_episodios['rating'], color='skyblue')
plt.xlabel('Rating')
plt.ylabel('Director')
plt.title('Mejores Episodios por Director')
plt.gca().invert_yaxis()  # Invierte el orden para mostrar los ratings más altos arriba
plt.tight_layout()
plt.show()